const { app } = require('@azure/functions');
const { GoogleAuth } = require('google-auth-library');
const { jsonResponse, handleOptions, getGcpConfig } = require('../lib/http');

app.http('generate-music', {
  methods: ['POST', 'OPTIONS'],
  authLevel: 'anonymous',
  route: 'generate-music',
  handler: async (request, context) => {
    const options = handleOptions(request);
    if (options) return options;

    const gcp = getGcpConfig(request);
    if (gcp.error) return gcp.error;

    try {
      const { prompt } = await request.json();

      if (!prompt) {
        return jsonResponse(400, { error: 'Missing prompt' }, request);
      }

      context.log('generate-music: Authenticating to Google Cloud...');
      const auth = new GoogleAuth({
        credentials: gcp.credentials,
        scopes: 'https://www.googleapis.com/auth/cloud-platform',
      });
      const client = await auth.getClient();
      const tokenResponse = await client.getAccessToken();
      const accessToken = tokenResponse.token || tokenResponse;

      // Vertex AI Endpoint for lyria-002 (widely accessible foundation model)
      const url = `https://${gcp.location}-aiplatform.googleapis.com/v1/projects/${gcp.projectId}/locations/${gcp.location}/publishers/google/models/lyria-002:predict`;

      const payload = {
        instances: [{ prompt }],
      };

      context.log('generate-music: Calling lyria-002 predict API...');
      const res = await fetch(url, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${accessToken}`,
        },
        body: JSON.stringify(payload),
      });

      if (!res.ok) {
        const errText = await res.text();
        context.error('Vertex AI Lyria Error:', errText);
        return jsonResponse(res.status, { error: `Vertex AI Lyria error ${res.status}: ${errText}` }, request);
      }

      const data = await res.json();
      
      // Extract predictions base64 audio
      const prediction = data.predictions?.[0];
      if (!prediction || !prediction.bytesBase64Encoded) {
        context.error('No audio found in response:', JSON.stringify(data));
        return jsonResponse(500, { error: 'No audio generated by the model.' }, request);
      }

      return jsonResponse(200, {
        audio: prediction.bytesBase64Encoded,
        mimeType: 'audio/wav', // lyria-002 outputs 48kHz WAV
      }, request);

    } catch (err) {
      context.error('generate-music error:', err);
      return jsonResponse(500, { error: err.message || 'Internal error' }, request);
    }
  },
});
