const { app } = require('@azure/functions');
const { GoogleAuth } = require('google-auth-library');
const { jsonResponse, handleOptions, getGcpConfig } = require('../lib/http');

app.http('generate-music', {
  methods: ['POST', 'OPTIONS'],
  authLevel: 'anonymous',
  route: 'generate-music',
  handler: async (request, context) => {
    const options = handleOptions(request);
    if (options) return options;

    const gcp = getGcpConfig(request);
    if (gcp.error) return gcp.error;

    try {
      const { prompt, imageBase64, imageMimeType } = await request.json();

      if (!prompt) {
        return jsonResponse(400, { error: 'Missing prompt' }, request);
      }

      context.log('generate-music: Authenticating to Google Cloud...');
      const auth = new GoogleAuth({
        credentials: gcp.credentials,
        scopes: 'https://www.googleapis.com/auth/cloud-platform',
      });
      const client = await auth.getClient();
      const tokenResponse = await client.getAccessToken();
      const accessToken = tokenResponse.token || tokenResponse;

      // Lyria 3 Clip is served from the 'global' Vertex AI endpoint
      const url = `https://aiplatform.googleapis.com/v1/projects/${gcp.projectId}/locations/global/publishers/google/models/lyria-3-clip-preview:generateContent`;

      // Build multimodal parts: text prompt + optional image input
      const parts = [{ text: prompt }];
      if (imageBase64 && imageMimeType) {
        parts.push({
          inlineData: {
            mimeType: imageMimeType,
            data: imageBase64,
          },
        });
      }

      const payload = {
        contents: [{
          role: 'user',
          parts,
        }],
        generationConfig: {
          responseModalities: ['AUDIO', 'TEXT'],
        },
      };

      context.log('generate-music: Calling Lyria 3 generateContent API...');
      const res = await fetch(url, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${accessToken}`,
        },
        body: JSON.stringify(payload),
      });

      if (!res.ok) {
        const errText = await res.text();
        context.error('Vertex AI Lyria Error:', errText);
        return jsonResponse(res.status, { error: `Vertex AI Lyria error ${res.status}: ${errText}` }, request);
      }

      const data = await res.json();
      
      // Walk parts in response to extract audio (it contains lyrics and audio parts)
      const candidates = data.candidates || [];
      const responseParts = candidates[0]?.content?.parts || [];
      let audioBase64 = null;
      let audioMimeType = null;
      let lyrics = null;

      for (const part of responseParts) {
        const inline = part.inlineData || part.inline_data;
        if (inline && typeof inline.data === 'string') {
          audioBase64 = inline.data;
          audioMimeType = inline.mimeType || inline.mime_type || 'audio/mpeg';
        } else if (part.text) {
          // Store first text part as lyrics/lyrics details
          if (!lyrics) lyrics = part.text;
        }
      }

      if (!audioBase64) {
        context.error('No audio found in Lyria response parts:', JSON.stringify(data));
        return jsonResponse(500, { error: 'No audio generated by the model.' }, request);
      }

      return jsonResponse(200, {
        audio: audioBase64,
        mimeType: audioMimeType,
        lyrics: lyrics,
      }, request);

    } catch (err) {
      context.error('generate-music error:', err);
      return jsonResponse(500, { error: err.message || 'Internal error' }, request);
    }
  },
});
