const { app } = require('@azure/functions');
const { GoogleAuth } = require('google-auth-library');
const { jsonResponse, handleOptions, getGcpConfig } = require('../lib/http');

app.http('generate-music', {
  methods: ['POST', 'OPTIONS'],
  authLevel: 'anonymous',
  route: 'generate-music',
  handler: async (request, context) => {
    const options = handleOptions(request);
    if (options) return options;

    const gcp = getGcpConfig(request);
    if (gcp.error) return gcp.error;

    try {
      const { prompt, imageBase64, imageMimeType } = await request.json();

      if (!prompt) {
        return jsonResponse(400, { error: 'Missing prompt' }, request);
      }

      context.log('generate-music: Authenticating to Google Cloud...');
      const auth = new GoogleAuth({
        credentials: gcp.credentials,
        scopes: 'https://www.googleapis.com/auth/cloud-platform',
      });
      const client = await auth.getClient();
      const tokenResponse = await client.getAccessToken();
      const accessToken = tokenResponse.token || tokenResponse;

      // Vertex AI Endpoint for Lyria 3 Clip
      const url = `https://${gcp.location}-aiplatform.googleapis.com/v1/projects/${gcp.projectId}/locations/${gcp.location}/publishers/google/models/lyria-3-clip-preview:generateContent`;

      // Build multimodal parts
      const parts = [{ text: prompt }];
      if (imageBase64 && imageMimeType) {
        parts.push({
          inlineData: {
            mimeType: imageMimeType,
            data: imageBase64,
          },
        });
      }

      const payload = {
        contents: [{
          role: 'user',
          parts,
        }],
        generationConfig: {
          responseModalities: ['AUDIO'],
        },
      };

      context.log('generate-music: Calling Lyria 3 Clip API...');
      const res = await fetch(url, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${accessToken}`,
        },
        body: JSON.stringify(payload),
      });

      if (!res.ok) {
        const errText = await res.text();
        context.error('Vertex AI Lyria Error:', errText);
        return jsonResponse(res.status, { error: `Vertex AI Lyria error ${res.status}: ${errText}` }, request);
      }

      const data = await res.json();
      
      // Extract audio data from the candidates response
      const audioPart = data.candidates?.[0]?.content?.parts?.find(part => part.inlineData);
      if (!audioPart || !audioPart.inlineData) {
        context.error('No audio part found in response:', JSON.stringify(data));
        return jsonResponse(500, { error: 'No audio generated by the model.' }, request);
      }

      return jsonResponse(200, {
        audio: audioPart.inlineData.data,
        mimeType: audioPart.inlineData.mimeType || 'audio/mpeg',
      }, request);

    } catch (err) {
      context.error('generate-music error:', err);
      return jsonResponse(500, { error: err.message || 'Internal error' }, request);
    }
  },
});
